// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Helper function for Prompt Expert to update agent prompts
export async function updateAgentPrompt(agentSlugOrId: string, newSystemPrompt: string, updatedBy?: string) {
  return supabase.functions.invoke('update-agent-prompt', {
    body: { 
      agentSlugOrId, 
      newSystemPrompt,
      updatedBy 
    }
  });
}

// Helper to update filter agent prompt
export async function updateFilterPrompt(
  newPromptContent: string, 
  filterVersion?: string,
  notes?: string
) {
  const { data: userData } = await supabase.auth.getUser();
  return supabase.functions.invoke('update-filter-prompt', {
    body: { 
      newPromptContent,
      filterVersion,
      notes,
      updatedBy: userData.user?.id,
    }
  });
}

// Helper to force knowledge alignment analysis
export async function forceAlignmentAnalysis(agentId: string) {
  // Extract requirements
  await supabase.functions.invoke('extract-task-requirements', {
    body: { agentId }
  });
  
  // Analyze alignment with force flag
  return supabase.functions.invoke('analyze-knowledge-alignment', {
    body: { 
      agentId,
      forceReanalysis: true
    }
  });
}

// Helper to force re-extraction with cache invalidation
export async function forceReExtraction(agentId: string) {
  // Step 1: Restore all removed chunks FIRST (fresh start)
  await supabase.from('agent_knowledge')
    .update({ 
      is_active: true,
      removal_reason: null,
      removed_at: null
    })
    .eq('agent_id', agentId)
    .eq('is_active', false);
  
  // Step 2: Invalidate cache
  await supabase.from('agent_task_requirements')
    .update({ 
      extracted_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
      system_prompt_hash: 'force-reextract'
    })
    .eq('agent_id', agentId);
  
  // Step 3: Re-extract requirements
  await supabase.functions.invoke('extract-task-requirements', {
    body: { agentId }
  });
  
  // Step 4: Re-analyze alignment with forceReanalysis flag
  return supabase.functions.invoke('analyze-knowledge-alignment', {
    body: { 
      agentId,
      forceReanalysis: true
    }
  });
}