// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Helper function for Prompt Expert to update agent prompts
export async function updateAgentPrompt(agentSlugOrId: string, newSystemPrompt: string, updatedBy?: string) {
  return supabase.functions.invoke('update-agent-prompt', {
    body: { 
      agentSlugOrId, 
      newSystemPrompt,
      updatedBy 
    }
  });
}

// Helper to update filter agent prompt
export async function updateFilterPrompt(
  newPromptContent: string, 
  filterVersion?: string,
  notes?: string
) {
  const { data: userData } = await supabase.auth.getUser();
  return supabase.functions.invoke('update-filter-prompt', {
    body: { 
      newPromptContent,
      filterVersion,
      notes,
      updatedBy: userData.user?.id,
    }
  });
}

// Helper to force knowledge alignment analysis
export async function forceAlignmentAnalysis(agentId: string) {
  // Extract requirements
  await supabase.functions.invoke('extract-task-requirements', {
    body: { agentId }
  });
  
  // Analyze alignment with force flag
  return supabase.functions.invoke('analyze-knowledge-alignment', {
    body: { 
      agentId,
      forceReanalysis: true
    }
  });
}